project:
  type: website
execute: 
  freeze: auto
website:
  title: "MoveNext Blog"
  twitter-card: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics: 
    tracking-id: "G-31V1GX81KD"
    storage: none


  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css